"""cartas entrega

Revision ID: f2575f14a74c
Revises: 
Create Date: 2025-09-30 19:34:49.390942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2575f14a74c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartas_diversas', sa.Column('entregue_bl', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.add_column('cartas_diversas', sa.Column('entregue_por_email', sa.Text(), nullable=True))
    op.add_column('cartas_diversas', sa.Column('entregue_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_cartas_entregue', 'cartas_diversas', ['entregue_bl'], unique=False, schema='public')
    op.drop_constraint('cartas_diversas_adotante_email_fkey', 'cartas_diversas', type_='foreignkey')
    op.create_foreign_key(None, 'cartas_diversas', 'usuarios', ['entregue_por_email'], ['email'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'cartas_diversas', 'usuarios', ['adotante_email'], ['email'], source_schema='public', referent_schema='public')
    op.drop_constraint('user_roles_user_email_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'user_roles', 'usuarios', ['user_email'], ['email'], source_schema='public', referent_schema='public')
    op.drop_constraint('usuarios_id_modulo_fkey', 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'modulo', ['id_modulo'], ['id_modulo'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', schema='public', type_='foreignkey')
    op.create_foreign_key('usuarios_id_modulo_fkey', 'usuarios', 'modulo', ['id_modulo'], ['id_modulo'])
    op.drop_constraint(None, 'user_roles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', schema='public', type_='foreignkey')
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('user_roles_user_email_fkey', 'user_roles', 'usuarios', ['user_email'], ['email'])
    op.drop_constraint(None, 'cartas_diversas', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'cartas_diversas', schema='public', type_='foreignkey')
    op.create_foreign_key('cartas_diversas_adotante_email_fkey', 'cartas_diversas', 'usuarios', ['adotante_email'], ['email'])
    op.drop_index('idx_cartas_entregue', table_name='cartas_diversas', schema='public')
    op.drop_column('cartas_diversas', 'entregue_em')
    op.drop_column('cartas_diversas', 'entregue_por_email')
    op.drop_column('cartas_diversas', 'entregue_bl')
    # ### end Alembic commands ###
